CREATE TABLE IF NOT EXISTS typeOperation(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description text NOT NULL CHECK (description <> '')
);
CREATE TABLE IF NOT EXISTS operations(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    valueOne float NOT NULL,
    valueTwo float NOT NULL,
    id_typeOperation integer REFERENCES typeOperation(id),
    result float NOT NULL
);

INSERT INTO typeOperation (description) VALUES ('Sum');
INSERT INTO typeOperation (description) VALUES ('Substraction');
INSERT INTO typeOperation (description) VALUES ('Multiplication');
INSERT INTO typeOperation (description) VALUES ('Divide');

